### PR TITLE
Ensure validators are registered before staking

### LINKED ISSUE #70: Reject unknown validators for external staking
I was testing with a provider chain validator address that got accepted and eventually failed in epoch rebalance on the consumer side. This should fail faster

### PR DESCRIPTION
**Pull request by ethanfrey**
Closes #70 

This doesn't let a new stake occur unless when know the validator is in the active set.
Added a test command to place a validator in the active set.

### CODE REVIEW

File: contracts/provider/external-staking/src/multitest.rs [hunk 1]
```diff
@@ -115,6 +125,23 @@ fn staking() {
         .call(users[1])
         .unwrap();
 
+    /*
```
Comment (ethanfrey) [inline contracts/provider/external-staking/src/multitest.rs:128]: @hashedone @jawoznia 

Another non-blocking issue in Sylvia.

User calls contract A. contract A returns message to execute contract B. contract B calls fail (no reply registered). A and B both have different ContractError registered.

The caller doesn't ever get the result, but it fails inside ExecProxy when trying to downcast the result to vault::ContractError (contract A). Not sure if the error is external_staking::ContractError (contract B), or StdError, but I want to assert this fails without panic-ing the test

**Comment by ethanfrey** [comment]
Merging this one. Happy for more detailed review later.
